test: add tests for update with exists=false precondition
googleapis/conformance-tests pull request #84
Opened 2024-01-20 02:29 UTC by dconeybe

This is a follow-up to https://github.com/googleapis/conformance-tests/pull/82 which updated the test for the exists precondition.

2024-01-20 02:30 UTC, dconeybe commented
@jskeet FYI

2024-01-22 07:22 UTC, jskeet approved these changes
Looks fine to me (albeit a little odd as this is effectively "create" isn't it?). Testing it against the current .NET implementation would be slightly fiddly, but I expect it to be fine.

2024-01-22 15:37 UTC, jskeet requested changes
Undoing previous LGTM - it's not clear whether we *do* want to prohibit this. (We've never prohibited it in .NET - are we sure this won't break people? What does the server do?)

2024-01-22 15:37 UTC, jskeet commented on firestore/v1/update-exists-false-precond.json
> +        "request": {
As noted in chat, let's remove this given that it's meant to be an error.

2024-01-22 15:54 UTC, jskeet approved these changes
Much clearer, thanks. And I've verified that it won't break the public API surface for .NET as we don't allow public specification of that precondition anywhere. (I'll need to add validation into the method in order to get the conformance tests to pass, but that's okay.)

2024-01-22 15:55 UTC, dconeybe commented
@ddelgrosso1 Are you able and willing to give approval for this PR too? It's a follow-up to https://github.com/googleapis/conformance-tests/pull/82. Feel free to DM me and/or @jskeet if you would like any clarifications. Thank you.

2024-01-23 07:28 UTC, merged